### ISSUE TITLE
Name change log weirdness

### ISSUE THREAD

**Issue by SevenSpheres** [UtopicUnicorns/ArtemisV3#12]
I've been seeing issues like this for some time, but here's the most recent example:
![artemislog1](https://user-images.githubusercontent.com/56284207/117201639-e0161d00-adba-11eb-85ad-59cf7b0e58a6.png)
![artemislog2](https://user-images.githubusercontent.com/56284207/117201771-063bbd00-adbb-11eb-8708-5ebe92cdcce7.png)
The nickname change was posted *three* times, and the "old usernames" never existed.
(Edit: name removed at user's request)

**Comment by UtopicUnicorns** [comment]
I thought I fixed this bug, clearly not..
I will fix this tomorrow (if I can of course), the usernames are most definitly real, but not from that member most likely and not in your server either..
Don't idk about the details, it weirds me out too

**Comment by UtopicUnicorns** [comment]
Should be fixed now... I hope.

**Comment by GurrenLagannTSS** [comment]
I'm reopening it to note that the bug still hasnt fixed, and i was able to replicate it.
Its likely related to how Artemis gathers nicknames and how it shows the nickname changes.

First, i changed my nickname on server 1 (Interstellcord II), note that the old nickname is also the then-current one on server 2:
![Screenshot_20210602-205708.png](https://user-images.githubusercontent.com/54154710/120566656-1492ee00-c3e6-11eb-91db-f962fb50013f.png)
Next, i changed my nickname on server 2 (the oficial Celestia server). Notice how the old nickname is now the one i set on Interstellcord II:
![Screenshot_20210602-210335.png](https://user-images.githubusercontent.com/54154710/120566710-2f656280-c3e6-11eb-82da-b52616e0c7e1.png)

**Comment by UtopicUnicorns** [comment]
Yeah it gathers the nicknames compares it to the old one and then shoots it out regardless of the server, will fix this a bit later.

**Comment by UtopicUnicorns** [comment]
Can you check if the bug is fixed?

**Comment by GurrenLagannTSS** [comment]
It seems to be fixed!

Server 1/Interstellcord II (two nickname changes to get the nickname to show up in the logs):
![Screenshot_20210603-093813.png](https://user-images.githubusercontent.com/54154710/120646103-8f442380-c44f-11eb-9078-f03d297ecf6d.png)
Server 2/Celestia (same note as before):
![Screenshot_20210603-093839.png](https://user-images.githubusercontent.com/54154710/120646250-b569c380-c44f-11eb-911a-8c01b7839681.png)

**Comment by UtopicUnicorns** [comment]
Let me investigate the side effect for a bit.
I saw it a while ago myself.

**Comment by UtopicUnicorns** [comment]
Should be patched now, please check if it still happens.

**Comment by UtopicUnicorns** [comment]
I have not seen the side effect pop up anymore, so I am considering this fixed.
